### ISSUE TITLE
please update to work with acuparse 3.x

### ISSUE THREAD

**Issue by TJLTM** [garyt72/sensor.acuparse#1]
I know that they changed the way the database is laid out in the 3.x version of acuparse and I suck at doing DB stuff. any idea if you're going to update this to work with acuparse 3.x?

**Comment by rct** [comment]
FYI - If you are running Acuparse 3.3.x (or presumably later), there is now a JSON REST interface so you can do much of what the acuparse sensor did by adding REST sensors to Home Assistant.

See https://docs.acuparse.com/API/ 

The data structure returned has a lot in it.  I need to re-do my Acuparse REST sensors now that Home Assistant redid the REST sensor making it easier to have a single REST endpoint defined that can yield multiple sensors and binary sensors.

Here's what I currently have that needs to be improved.  Right now most of the fields are attributes.

```
---
#
# Acuparse 3.x REST sensors via JSON
#

sensor acuparse:
- platform: rest
  name: acuparse_5n1_temperature
  resource: http://acuparse.local/api/v1/json/dashboard/?main
  scan_interval: 150
  json_attributes_path: "$.main"
  value_template: '{{ value_json["main"]["tempF"] }}'
  unit_of_measurement: '°F'
  json_attributes:
    - feelsF
    - tempF_trend
    - tempF_high
    - high_temp_recorded
    - tempF_low
    - low_temp_recorded
    - relH
    - relH_trend
    - pressure_inHg
    - pressure_trend
    - windSppedMPH
    - windDIR
    - windDEG
    - windSpeedMPH_peak
    - windDIR_peak
    - windDEG_peak
    - windSpeed_peak_recorded
    - windBeaufort
    - moonrise
    - moonset
    - moon_nextFull
    - lastUpdated

- platform: template
  sensors:
    acuparse_pressure:
      friendly_name: 'Acuparse Pressure'
      value_template: '{{ state_attr("sensor.acuparse_5n1_temperature", "pressure_inHg") }
} '
      unit_of_measurement: 'inHg'
    acuparse_feels_temperature:
      friendly_name: 'Acuparse Feels-like temperature'
      value_template: '{{ state_attr("sensor.acuparse_5n1_temperature", "feelsF") }} '
      # value_template: '{{ "unknown" if state_attr("sensor.acuparse_5n1_temperature", "fe
elsF") == 0 else  state_attr("sensor.acuparse_5n1_temperature", "feelsF") | float }}'
      unit_of_measurement: '°F'
    acuparse_moonrise:
      friendly_name: 'Acuparse Moonrise'
      value_template: '{{ state_attr("sensor.acuparse_5n1_temperature", "moonrise") }} '
    acuparse_moonset:
      friendly_name: 'Acuparse Moonset'
      value_template: '{{ state_attr("sensor.acuparse_5n1_temperature", "moonset") }} '
    acuparse_moon_illumination:
      friendly_name: 'Acuparse Moon Illumination'
      value_template: '{{ state_attr("sensor.acuparse_5n1_temperature", "moon_illumination
") }} '

```

![image](https://user-images.githubusercontent.com/38770/118504792-d5804f80-b6f9-11eb-91ab-db33d59d689c.png)


There is also a system status rest API end point that can be mostly used to monitor the Acurite Access' reception of your devices.
